const PANELS = {
  FETCH: "FETCH_PANELS",
  FETCH_SUCCESS: "FETCH_PANELS_SUCCESS",
  FETCH_FAIL: "FETCH_PANELS_FAIL"
};

const THEME = {
  CHANGE: "THEME_CHANGE"
};

const ARTICLES = {
  FETCH: "ARTICLES_FETCH",
  FETCH_MORE: "ARTICLES_FETCH_MORE",
  FETCH_SUCCESS: "ARTICLES_FETCH_SUCCESS",
  FETCH_FAIL: "ARTICLES_FETCH_FAIL"
};

export { PANELS, THEME, ARTICLES };
