const PANELS = {
  FETCH: "FETCH_PANELS",
  FETCH_SUCCESS: "FETCH_PANELS_SUCCESS",
  FETCH_FAIL: "FETCH_PANELS_FAIL"
};

const THEME = {
  CHANGE: "THEME_CHANGE"
};

const INDEX_ARTICLES = {
  FETCH: "INDEX_ARTICLES_FETCH",
  FETCH_MORE: "INDEX_ARTICLES_FETCH_MORE",
  FETCH_SUCCESS: "INDEX_ARTICLES_FETCH_SUCCESS",
  FETCH_FAIL: "INDEX_ARTICLES_FETCH_FAIL"
};

export { PANELS, THEME, INDEX_ARTICLES };
